import { StatusBar } from 'expo-status-bar';
import { useEffect, useMemo, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { database, Measurement } from './src/database';
import { analyzeMeasurements, demoMeasurements } from './src/domain';
import { Language, strings } from './src/i18n';

type Screen = 'home' | 'tests' | 'entry' | 'settings';
const colors = { ink: '#102A2B', muted: '#657577', teal: '#0C7C72', tealDark: '#075B55', mint: '#E5F5F0', lime: '#D9F077', cream: '#F7F7F2', white: '#FFFFFF', line: '#DDE5E1', amber: '#E59A2F' };

export default function App() {
  const [screen, setScreen] = useState<Screen>('home');
  const [language, setLanguage] = useState<Language>(() => Intl.DateTimeFormat().resolvedOptions().locale.toLowerCase().startsWith('de') ? 'de' : 'en');
  const [measurements, setMeasurements] = useState<Measurement[]>([]);
  const [isReady, setIsReady] = useState(false);
  const t = strings[language];
  useEffect(() => { database.initialize().then(async () => { const saved = await database.listMeasurements(); setMeasurements(saved.length ? saved : demoMeasurements); setIsReady(true); }); }, []);
  const analysis = useMemo(() => analyzeMeasurements(measurements), [measurements]);
  const saveMeasurement = async (measurement: Measurement) => { await database.saveMeasurement(measurement); setMeasurements(await database.listMeasurements()); setScreen('home'); };
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" /><View style={styles.app}><Header language={language} proLabel={t.pro} /><View style={styles.content}>
    {screen === 'home' && <Dashboard t={t} analysis={analysis} ready={isReady} onNew={() => setScreen('entry')} />}
    {screen === 'tests' && <Tests t={t} analysis={analysis} onNew={() => setScreen('entry')} />}
    {screen === 'entry' && <Entry t={t} language={language} onSave={saveMeasurement} />}
    {screen === 'settings' && <Settings t={t} language={language} onLanguage={setLanguage} />}
  </View><Navigation screen={screen} setScreen={setScreen} t={t} /></View></SafeAreaView>;
}

function Header({ language, proLabel }: { language: Language; proLabel: string }) { return <View style={styles.header}><View><Text style={styles.brand}>WärmeTakt</Text><Text style={styles.brandLine}>{language === 'de' ? 'KLARER HEIZEN' : 'HEAT SMARTER'}</Text></View><View style={styles.proPill}><Text style={styles.proPillText}>◇ {proLabel}</Text></View></View>; }

function Dashboard({ t, analysis, ready, onNew }: any) { return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
  <Text style={styles.eyebrow}>{t.overview}</Text><Text style={styles.title}>{t.greeting}</Text><Text style={styles.subtitle}>{t.intro}</Text>
  <View style={styles.heroCard}><View style={styles.heroTop}><View><Text style={styles.heroLabel}>{t.efficiencyChange}</Text><Text style={styles.heroValue}>{ready ? `${analysis.change > 0 ? '+' : ''}${analysis.change}%` : '–'}</Text></View><View style={styles.scoreCircle}><Text style={styles.score}>{analysis.score}</Text><Text style={styles.scoreOf}>/100</Text></View></View><View style={styles.divider} /><Text style={styles.heroText}>{analysis.change > 0 ? t.resultPositive : t.resultWaiting}</Text><View style={styles.miniRow}><Metric value={analysis.cop.toFixed(2)} label={t.cop} /><Metric value={`${analysis.cyclesChange}%`} label={t.fewerStarts} /><Metric value={`${analysis.comfort.toFixed(1)} °C`} label={t.comfort} /></View></View>
  <View style={styles.sectionRow}><Text style={styles.sectionTitle}>{t.activeTest}</Text><Text style={styles.link}>{t.details}</Text></View>
  <View style={styles.testCard}><View style={styles.testIcon}><Text style={styles.testIconText}>↘</Text></View><View style={styles.testContent}><Text style={styles.testTitle}>{t.heatingCurve}</Text><Text style={styles.testMeta}>{t.dayOfTest}</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: '58%' }]} /></View><Text style={styles.testHint}>{t.weatherAdjusted}</Text></View></View>
  <Pressable style={styles.primaryButton} onPress={onNew}><Text style={styles.primaryButtonText}>＋  {t.addMeasurement}</Text></Pressable><Text style={styles.disclaimer}>{t.disclaimer}</Text>
</ScrollView>; }

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }

function Tests({ t, analysis, onNew }: any) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>{t.experiments}</Text><Text style={styles.title}>{t.testsTitle}</Text><Text style={styles.subtitle}>{t.testsIntro}</Text><View style={styles.resultCard}><Text style={styles.badge}>{t.inProgress}</Text><Text style={styles.resultTitle}>{t.heatingCurve}</Text><Text style={styles.settingChange}>0.6  →  0.5</Text><View style={styles.compareRow}><View><Text style={styles.compareLabel}>{t.before}</Text><Text style={styles.compareValue}>5.7 kWh</Text></View><View><Text style={styles.compareLabel}>{t.after}</Text><Text style={[styles.compareValue, { color: colors.teal }]}>5.0 kWh</Text></View><View><Text style={styles.compareLabel}>{t.adjusted}</Text><Text style={[styles.compareValue, { color: colors.teal }]}>+{analysis.change}%</Text></View></View><Text style={styles.resultNote}>{t.needMoreDays}</Text></View><Pressable style={styles.primaryButton} onPress={onNew}><Text style={styles.primaryButtonText}>＋  {t.newTest}</Text></Pressable></ScrollView>; }

function Entry({ t, language, onSave }: { t: any; language: Language; onSave: (m: Measurement) => void }) {
  const [electricity, setElectricity] = useState('5.1'), [heat, setHeat] = useState('18.4'), [outside, setOutside] = useState('4.2'), [room, setRoom] = useState('21.0'), [starts, setStarts] = useState('8');
  const number = (value: string) => Number(value.replace(',', '.')) || 0;
  const submit = () => onSave({ id: String(Date.now()), measuredAt: new Date().toISOString(), phase: 'after', electricityKwh: number(electricity), heatKwh: number(heat), outsideC: number(outside), roomC: number(room), compressorStarts: number(starts) });
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>{t.dailyValues}</Text><Text style={styles.title}>{t.entryTitle}</Text><Text style={styles.subtitle}>{t.entryIntro}</Text><View style={styles.formCard}><Field label={t.electricity} unit="kWh" value={electricity} onChange={setElectricity} language={language} /><Field label={t.generatedHeat} unit="kWh" value={heat} onChange={setHeat} language={language} /><Field label={t.outsideTemp} unit="°C" value={outside} onChange={setOutside} language={language} /><Field label={t.roomTemp} unit="°C" value={room} onChange={setRoom} language={language} /><Field label={t.compressorStarts} unit={t.count} value={starts} onChange={setStarts} language={language} /></View><Pressable style={styles.primaryButton} onPress={submit}><Text style={styles.primaryButtonText}>{t.saveAndAnalyze}</Text></Pressable><Text style={styles.formHint}>{t.localStorage}</Text></ScrollView></KeyboardAvoidingView>;
}

function Field({ label, unit, value, onChange, language }: any) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><View style={styles.inputWrap}><TextInput style={styles.input} value={value} onChangeText={onChange} keyboardType="decimal-pad" placeholder={language === 'de' ? '0,0' : '0.0'} accessibilityLabel={label} /><Text style={styles.unit}>{unit}</Text></View></View>; }

function Settings({ t, language, onLanguage }: { t: any; language: Language; onLanguage: (l: Language) => void }) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>{t.settings}</Text><Text style={styles.title}>{t.settingsTitle}</Text><View style={styles.settingsCard}><Text style={styles.fieldLabel}>{t.language}</Text><View style={styles.segment}>{(['de', 'en'] as Language[]).map((item) => <Pressable key={item} style={[styles.segmentItem, language === item && styles.segmentActive]} onPress={() => onLanguage(item)}><Text style={[styles.segmentText, language === item && styles.segmentTextActive]}>{item === 'de' ? 'Deutsch' : 'English'}</Text></Pressable>)}</View></View><View style={styles.proCard}><Text style={styles.proCardEyebrow}>WÄRMETAKT PRO</Text><Text style={styles.proCardTitle}>{t.unlockTitle}</Text><Text style={styles.proCardText}>{t.unlockText}</Text><Text style={styles.price}>39,99 € <Text style={styles.once}>{t.once}</Text></Text><Pressable style={styles.proButton}><Text style={styles.proButtonText}>{t.unlock}</Text></Pressable><Text style={styles.restore}>{t.restore}</Text></View><Text style={styles.version}>WärmeTakt 1.0.0 · Kamilunavo</Text></ScrollView>; }

function Navigation({ screen, setScreen, t }: { screen: Screen; setScreen: (s: Screen) => void; t: any }) { const items: { key: Screen; icon: string; label: string }[] = [{ key: 'home', icon: '⌂', label: t.home }, { key: 'tests', icon: '↗', label: t.tests }, { key: 'entry', icon: '＋', label: t.entry }, { key: 'settings', icon: '⚙', label: t.settings }]; return <View style={styles.nav}>{items.map((item) => <Pressable key={item.key} style={styles.navItem} onPress={() => setScreen(item.key)}><Text style={[styles.navIcon, screen === item.key && styles.navActive]}>{item.icon}</Text><Text style={[styles.navLabel, screen === item.key && styles.navActive]}>{item.label}</Text></Pressable>)}</View>; }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.white }, app: { flex: 1, backgroundColor: colors.cream }, content: { flex: 1 },
  header: { height: 76, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.line },
  brand: { color: colors.ink, fontSize: 24, fontWeight: '800', letterSpacing: -0.8 }, brandLine: { color: colors.teal, fontSize: 9, fontWeight: '800', letterSpacing: 2.2, marginTop: 1 }, proPill: { backgroundColor: colors.mint, borderRadius: 20, paddingHorizontal: 13, paddingVertical: 8 }, proPillText: { color: colors.tealDark, fontWeight: '800', fontSize: 12 }, scroll: { padding: 22, paddingBottom: 36 },
  eyebrow: { color: colors.teal, fontWeight: '800', fontSize: 11, letterSpacing: 1.7, textTransform: 'uppercase', marginTop: 4 }, title: { color: colors.ink, fontSize: 31, lineHeight: 36, fontWeight: '800', letterSpacing: -1, marginTop: 7 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 20 },
  heroCard: { backgroundColor: colors.ink, borderRadius: 24, padding: 20 }, heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, heroLabel: { color: '#AFC1BF', fontSize: 12, fontWeight: '700' }, heroValue: { color: colors.lime, fontSize: 42, fontWeight: '800', letterSpacing: -1.5, marginTop: 2 }, scoreCircle: { width: 68, height: 68, borderRadius: 34, borderWidth: 5, borderColor: colors.teal, alignItems: 'center', justifyContent: 'center', flexDirection: 'row' }, score: { color: colors.white, fontWeight: '800', fontSize: 20 }, scoreOf: { color: '#9FB1AF', fontSize: 9, marginTop: 7 }, divider: { height: 1, backgroundColor: '#294344', marginVertical: 16 }, heroText: { color: colors.white, fontSize: 14, lineHeight: 20 }, miniRow: { flexDirection: 'row', marginTop: 18 }, metric: { flex: 1 }, metricValue: { color: colors.white, fontSize: 17, fontWeight: '800' }, metricLabel: { color: '#9FB1AF', fontSize: 10, lineHeight: 14, marginTop: 2 },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 25, marginBottom: 10 }, sectionTitle: { color: colors.ink, fontWeight: '800', fontSize: 17 }, link: { color: colors.teal, fontWeight: '700', fontSize: 12 }, testCard: { backgroundColor: colors.white, borderRadius: 18, padding: 16, flexDirection: 'row', borderWidth: 1, borderColor: colors.line }, testIcon: { width: 43, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.mint }, testIconText: { color: colors.teal, fontSize: 23, fontWeight: '800' }, testContent: { flex: 1, marginLeft: 13 }, testTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' }, testMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, progressTrack: { height: 6, borderRadius: 4, backgroundColor: '#E8EEEB', marginTop: 12 }, progressFill: { height: 6, borderRadius: 4, backgroundColor: colors.teal }, testHint: { color: colors.muted, fontSize: 10, marginTop: 7 },
  primaryButton: { backgroundColor: colors.teal, minHeight: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 18, paddingHorizontal: 16 }, primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: '800' }, disclaimer: { color: colors.muted, fontSize: 10, lineHeight: 15, textAlign: 'center', marginTop: 14, paddingHorizontal: 10 },
  resultCard: { backgroundColor: colors.white, borderRadius: 22, padding: 20, borderWidth: 1, borderColor: colors.line }, badge: { color: colors.amber, backgroundColor: '#FFF4DF', fontSize: 10, fontWeight: '800', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 10, alignSelf: 'flex-start', overflow: 'hidden' }, resultTitle: { color: colors.ink, fontSize: 21, fontWeight: '800', marginTop: 13 }, settingChange: { color: colors.teal, fontSize: 26, fontWeight: '800', marginTop: 5 }, compareRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.line }, compareLabel: { color: colors.muted, fontSize: 10, textTransform: 'uppercase', fontWeight: '700' }, compareValue: { color: colors.ink, fontWeight: '800', fontSize: 16, marginTop: 4 }, resultNote: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 18 },
  formCard: { backgroundColor: colors.white, borderRadius: 22, padding: 18, borderWidth: 1, borderColor: colors.line }, field: { marginBottom: 16 }, fieldLabel: { color: colors.ink, fontSize: 13, fontWeight: '700', marginBottom: 7 }, inputWrap: { height: 50, borderWidth: 1, borderColor: colors.line, borderRadius: 13, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAFBF9' }, input: { flex: 1, color: colors.ink, fontSize: 17, fontWeight: '700', paddingHorizontal: 14, height: '100%' }, unit: { color: colors.muted, fontSize: 13, fontWeight: '700', paddingRight: 14 }, formHint: { color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 12 },
  settingsCard: { backgroundColor: colors.white, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: colors.line, marginTop: 20 }, segment: { flexDirection: 'row', backgroundColor: colors.cream, padding: 4, borderRadius: 13 }, segmentItem: { flex: 1, paddingVertical: 11, alignItems: 'center', borderRadius: 10 }, segmentActive: { backgroundColor: colors.white }, segmentText: { color: colors.muted, fontWeight: '700' }, segmentTextActive: { color: colors.tealDark }, proCard: { backgroundColor: colors.ink, borderRadius: 24, padding: 22, marginTop: 18 }, proCardEyebrow: { color: colors.lime, fontSize: 10, fontWeight: '800', letterSpacing: 1.8 }, proCardTitle: { color: colors.white, fontSize: 24, fontWeight: '800', marginTop: 9 }, proCardText: { color: '#B7C6C4', fontSize: 13, lineHeight: 20, marginTop: 8 }, price: { color: colors.white, fontSize: 27, fontWeight: '800', marginTop: 18 }, once: { color: '#AFC1BF', fontSize: 12, fontWeight: '500' }, proButton: { backgroundColor: colors.lime, borderRadius: 14, padding: 15, alignItems: 'center', marginTop: 15 }, proButtonText: { color: colors.ink, fontWeight: '800' }, restore: { color: '#AFC1BF', textAlign: 'center', fontSize: 11, marginTop: 13 }, version: { color: colors.muted, textAlign: 'center', fontSize: 10, marginTop: 18 },
  nav: { height: 70, paddingBottom: 5, flexDirection: 'row', backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.line }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' }, navIcon: { color: '#7E8D8C', fontSize: 21, height: 26 }, navLabel: { color: '#7E8D8C', fontSize: 9, fontWeight: '700' }, navActive: { color: colors.teal },
});
