import { StatusBar } from 'expo-status-bar';
import { useEffect, useMemo, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { database, Experiment, Measurement } from './src/database';
import { analyzeMeasurements } from './src/domain';
import { flowStrings, Language, strings, unitStrings } from './src/i18n';
import { useProPurchase } from './src/useProPurchase';

type Screen = 'home' | 'tests' | 'newTest' | 'entry' | 'settings';
type UnitSystem = 'metric' | 'imperial';
const colors = { ink: '#102A2B', muted: '#657577', teal: '#0C7C72', tealDark: '#075B55', mint: '#E5F5F0', lime: '#D9F077', cream: '#F7F7F2', white: '#FFFFFF', line: '#DDE5E1', amber: '#E59A2F' };

export default function App() {
  const [screen, setScreen] = useState<Screen>('home');
  const [language, setLanguage] = useState<Language>(() => Intl.DateTimeFormat().resolvedOptions().locale.toLowerCase().startsWith('de') ? 'de' : 'en');
  const [unitSystem, setUnitSystem] = useState<UnitSystem>(() => Intl.DateTimeFormat().resolvedOptions().locale.toUpperCase().includes('-US') ? 'imperial' : 'metric');
  const [measurements, setMeasurements] = useState<Measurement[]>([]);
  const [experiments, setExperiments] = useState<Experiment[]>([]);
  const [isReady, setIsReady] = useState(false);
  const purchase = useProPurchase();
  const t = { ...strings[language], ...unitStrings[language], ...flowStrings[language] };
  useEffect(() => { database.initialize().then(async () => { setMeasurements(await database.listMeasurements()); setExperiments(await database.listExperiments()); setIsReady(true); }); }, []);
  const analysis = useMemo(() => analyzeMeasurements(measurements), [measurements]);
  const saveMeasurement = async (measurement: Measurement) => { await database.saveMeasurement(measurement); setMeasurements(await database.listMeasurements()); setScreen('home'); };
  const startTest = () => setScreen(!purchase.isPro && experiments.length >= 1 ? 'settings' : 'newTest');
  const saveExperiment = async (experiment: Experiment) => { await database.saveExperiment(experiment); setExperiments(await database.listExperiments()); setScreen('tests'); };
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" /><View style={styles.app}><Header language={language} proLabel={t.pro} /><View style={styles.content}>
    {screen === 'home' && <Dashboard t={t} analysis={analysis} ready={isReady} unitSystem={unitSystem} experiment={experiments[0]} onNew={() => setScreen('entry')} onNewTest={startTest} />}
    {screen === 'tests' && <Tests t={t} analysis={analysis} experiments={experiments} onNew={startTest} />}
    {screen === 'newTest' && <NewTest t={t} onSave={saveExperiment} onCancel={() => setScreen('tests')} />}
    {screen === 'entry' && <Entry t={t} language={language} unitSystem={unitSystem} onSave={saveMeasurement} />}
    {screen === 'settings' && <Settings t={t} language={language} unitSystem={unitSystem} purchase={purchase} onLanguage={setLanguage} onUnitSystem={setUnitSystem} />}
  </View><Navigation screen={screen} setScreen={setScreen} t={t} /></View></SafeAreaView>;
}

function Header({ language, proLabel }: { language: Language; proLabel: string }) { return <View style={styles.header}><View><Text style={styles.brand}>WärmeTakt</Text><Text style={styles.brandLine}>{language === 'de' ? 'KLARER HEIZEN' : 'HEAT SMARTER'}</Text></View><View style={styles.proPill}><Text style={styles.proPillText}>◇ {proLabel}</Text></View></View>; }

function Dashboard({ t, analysis, ready, unitSystem, experiment, onNew, onNewTest }: any) { const comfort = unitSystem === 'imperial' ? analysis.comfort * 9 / 5 + 32 : analysis.comfort; return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
  <Text style={styles.eyebrow}>{t.overview}</Text><Text style={styles.title}>{t.greeting}</Text><Text style={styles.subtitle}>{t.intro}</Text>
  <View style={styles.heroCard}><View style={styles.heroTop}><View><Text style={styles.heroLabel}>{t.efficiencyChange}</Text><Text style={styles.heroValue}>{ready ? `${analysis.change > 0 ? '+' : ''}${analysis.change}%` : '–'}</Text></View><View style={styles.scoreCircle}><Text style={styles.score}>{analysis.score}</Text><Text style={styles.scoreOf}>/100</Text></View></View><View style={styles.divider} /><Text style={styles.heroText}>{analysis.change > 0 ? t.resultPositive : t.resultWaiting}</Text><View style={styles.miniRow}><Metric value={analysis.cop.toFixed(2)} label={t.cop} /><Metric value={`${analysis.cyclesChange}%`} label={t.fewerStarts} /><Metric value={`${comfort.toFixed(1)} °${unitSystem === 'imperial' ? 'F' : 'C'}`} label={t.comfort} /></View></View>
  <View style={styles.sectionRow}><Text style={styles.sectionTitle}>{t.activeTest}</Text></View>
  {experiment ? <View style={styles.testCard}><View style={styles.testIcon}><Text style={styles.testIconText}>↘</Text></View><View style={styles.testContent}><Text style={styles.testTitle}>{t.settingNames[experiment.setting] ?? experiment.setting}</Text><Text style={styles.testMeta}>{experiment.previousValue} → {experiment.newValue} {experiment.unit}</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: '20%' }]} /></View><Text style={styles.testHint}>{t.weatherAdjusted}</Text></View></View> : <Pressable style={styles.emptyCard} onPress={onNewTest}><Text style={styles.emptyTitle}>{t.noActiveTest}</Text><Text style={styles.emptyText}>{t.noActiveTestText}</Text><Text style={styles.link}>{t.startFirstTest} →</Text></Pressable>}
  <Pressable style={styles.primaryButton} onPress={onNew}><Text style={styles.primaryButtonText}>＋  {t.addMeasurement}</Text></Pressable><Text style={styles.disclaimer}>{t.disclaimer}</Text>
</ScrollView>; }

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }

function Tests({ t, analysis, experiments, onNew }: any) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>{t.experiments}</Text><Text style={styles.title}>{t.testsTitle}</Text><Text style={styles.subtitle}>{t.testsIntro}</Text>{experiments.length ? experiments.map((experiment: Experiment) => <View style={styles.resultCard} key={experiment.id}><Text style={styles.badge}>{experiment.status === 'active' ? t.inProgress : t.completed}</Text><Text style={styles.resultTitle}>{t.settingNames[experiment.setting] ?? experiment.setting}</Text><Text style={styles.settingChange}>{experiment.previousValue}  →  {experiment.newValue} {experiment.unit}</Text><View style={styles.compareRow}><View><Text style={styles.compareLabel}>{t.duration}</Text><Text style={styles.compareValue}>{experiment.durationDays} {t.days}</Text></View><View><Text style={styles.compareLabel}>{t.adjusted}</Text><Text style={[styles.compareValue, { color: colors.teal }]}>{analysis.change > 0 ? '+' : ''}{analysis.change}%</Text></View></View><Text style={styles.resultNote}>{t.needMoreDays}</Text></View>) : <View style={styles.emptyCard}><Text style={styles.emptyTitle}>{t.noTests}</Text><Text style={styles.emptyText}>{t.noTestsText}</Text></View>}<Pressable style={styles.primaryButton} onPress={onNew}><Text style={styles.primaryButtonText}>＋  {t.newTest}</Text></Pressable></ScrollView>; }

function NewTest({ t, onSave, onCancel }: { t: any; onSave: (experiment: Experiment) => void; onCancel: () => void }) {
  const [step, setStep] = useState(1), [setting, setSetting] = useState('heatingCurve'), [previousValue, setPreviousValue] = useState('0.6'), [newValue, setNewValue] = useState('0.5'), [durationDays, setDurationDays] = useState(7), [confirmed, setConfirmed] = useState(false);
  const settings = ['heatingCurve', 'flowTemperature', 'hotWater', 'hysteresis', 'roomTarget', 'other'];
  const units: Record<string, string> = { heatingCurve: '', flowTemperature: '°C', hotWater: '°C', hysteresis: 'K', roomTarget: '°C', other: '' };
  const next = () => { if (step < 3) setStep(step + 1); else if (confirmed) onSave({ id: String(Date.now()), setting, previousValue, newValue, unit: units[setting], durationDays, startedAt: new Date().toISOString(), status: 'active' }); };
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.wizardTop}><Pressable onPress={onCancel}><Text style={styles.link}>‹ {t.cancel}</Text></Pressable><Text style={styles.stepLabel}>{t.step} {step}/3</Text></View><Text style={styles.eyebrow}>{t.newExperiment}</Text><Text style={styles.title}>{step === 1 ? t.chooseSetting : step === 2 ? t.enterChange : t.checkAndStart}</Text><Text style={styles.subtitle}>{step === 1 ? t.chooseSettingText : step === 2 ? t.enterChangeText : t.checkText}</Text>
    {step === 1 && <View>{settings.map((item) => <Pressable key={item} style={[styles.optionCard, setting === item && styles.optionActive]} onPress={() => setSetting(item)}><View style={[styles.radio, setting === item && styles.radioActive]} /> <Text style={[styles.optionText, setting === item && styles.optionTextActive]}>{t.settingNames[item]}</Text></Pressable>)}</View>}
    {step === 2 && <View><View style={styles.formCard}><Field label={t.previousValue} unit={units[setting]} value={previousValue} onChange={setPreviousValue} language="en" /><Field label={t.newValue} unit={units[setting]} value={newValue} onChange={setNewValue} language="en" /><Text style={styles.fieldLabel}>{t.testDuration}</Text><View style={styles.segment}>{[7, 14].map((days) => <Pressable key={days} style={[styles.segmentItem, durationDays === days && styles.segmentActive]} onPress={() => setDurationDays(days)}><Text style={[styles.segmentText, durationDays === days && styles.segmentTextActive]}>{days} {t.days}</Text></Pressable>)}</View></View><View style={styles.infoCard}><Text style={styles.infoTitle}>ⓘ {t.oneChangeOnly}</Text><Text style={styles.infoText}>{t.oneChangeOnlyText}</Text></View></View>}
    {step === 3 && <View><View style={styles.summaryCard}><SummaryRow label={t.setting} value={t.settingNames[setting]} /><SummaryRow label={t.change} value={`${previousValue} → ${newValue} ${units[setting]}`} /><SummaryRow label={t.testDuration} value={`${durationDays} ${t.days}`} /></View><Pressable style={[styles.confirmCard, confirmed && styles.confirmActive]} onPress={() => setConfirmed(!confirmed)}><View style={[styles.checkbox, confirmed && styles.checkboxActive]}><Text style={styles.checkmark}>{confirmed ? '✓' : ''}</Text></View><Text style={styles.confirmText}>{t.safetyConfirm}</Text></Pressable></View>}
    <View style={styles.wizardActions}>{step > 1 && <Pressable style={styles.secondaryButton} onPress={() => setStep(step - 1)}><Text style={styles.secondaryButtonText}>{t.back}</Text></Pressable>}<Pressable style={[styles.primaryButton, styles.wizardPrimary, step === 3 && !confirmed && styles.disabledButton]} disabled={step === 3 && !confirmed} onPress={next}><Text style={styles.primaryButtonText}>{step === 3 ? t.startTest : t.continue}</Text></Pressable></View>
  </ScrollView></KeyboardAvoidingView>;
}

function SummaryRow({ label, value }: { label: string; value: string }) { return <View style={styles.summaryRow}><Text style={styles.summaryLabel}>{label}</Text><Text style={styles.summaryValue}>{value}</Text></View>; }

function Entry({ t, language, unitSystem, onSave }: { t: any; language: Language; unitSystem: UnitSystem; onSave: (m: Measurement) => void }) {
  const [electricity, setElectricity] = useState('5.1'), [heat, setHeat] = useState('18.4'), [outside, setOutside] = useState(unitSystem === 'imperial' ? '39.6' : '4.2'), [room, setRoom] = useState(unitSystem === 'imperial' ? '69.8' : '21.0'), [starts, setStarts] = useState('8');
  const number = (value: string) => Number(value.replace(',', '.')) || 0;
  const toCelsius = (value: number) => unitSystem === 'imperial' ? (value - 32) * 5 / 9 : value;
  const submit = () => onSave({ id: String(Date.now()), measuredAt: new Date().toISOString(), phase: 'after', electricityKwh: number(electricity), heatKwh: number(heat), outsideC: toCelsius(number(outside)), roomC: toCelsius(number(room)), compressorStarts: number(starts) });
  const tempUnit = unitSystem === 'imperial' ? '°F' : '°C';
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>{t.dailyValues}</Text><Text style={styles.title}>{t.entryTitle}</Text><Text style={styles.subtitle}>{t.entryIntro}</Text><View style={styles.formCard}><Field label={t.electricity} unit="kWh" value={electricity} onChange={setElectricity} language={language} /><Field label={t.generatedHeat} unit="kWh" value={heat} onChange={setHeat} language={language} /><Field label={t.outsideTemp} unit={tempUnit} value={outside} onChange={setOutside} language={language} /><Field label={t.roomTemp} unit={tempUnit} value={room} onChange={setRoom} language={language} /><Field label={t.compressorStarts} unit={t.count} value={starts} onChange={setStarts} language={language} /></View><Pressable style={styles.primaryButton} onPress={submit}><Text style={styles.primaryButtonText}>{t.saveAndAnalyze}</Text></Pressable><Text style={styles.formHint}>{t.localStorage}</Text></ScrollView></KeyboardAvoidingView>;
}

function Field({ label, unit, value, onChange, language }: any) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><View style={styles.inputWrap}><TextInput style={styles.input} value={value} onChangeText={onChange} keyboardType="decimal-pad" placeholder={language === 'de' ? '0,0' : '0.0'} accessibilityLabel={label} /><Text style={styles.unit}>{unit}</Text></View></View>; }

function Settings({ t, language, unitSystem, purchase, onLanguage, onUnitSystem }: { t: any; language: Language; unitSystem: UnitSystem; purchase: ReturnType<typeof useProPurchase>; onLanguage: (l: Language) => void; onUnitSystem: (u: UnitSystem) => void }) {
  const price = purchase.price ?? (language === 'de' ? '39,99 €' : '$39.99');
  return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>{t.settings}</Text><Text style={styles.title}>{t.settingsTitle}</Text><View style={styles.settingsCard}><Text style={styles.fieldLabel}>{t.language}</Text><View style={styles.segment}>{(['de', 'en'] as Language[]).map((item) => <Pressable key={item} style={[styles.segmentItem, language === item && styles.segmentActive]} onPress={() => onLanguage(item)}><Text style={[styles.segmentText, language === item && styles.segmentTextActive]}>{item === 'de' ? 'Deutsch' : 'English'}</Text></Pressable>)}</View><Text style={[styles.fieldLabel, { marginTop: 18 }]}>{t.unitSystem}</Text><View style={styles.segment}>{(['metric', 'imperial'] as UnitSystem[]).map((item) => <Pressable key={item} style={[styles.segmentItem, unitSystem === item && styles.segmentActive]} onPress={() => onUnitSystem(item)}><Text style={[styles.segmentText, unitSystem === item && styles.segmentTextActive]}>{item === 'metric' ? t.celsius : t.fahrenheit}</Text></Pressable>)}</View></View><View style={styles.proCard}><Text style={styles.proCardEyebrow}>WÄRMETAKT PRO</Text><Text style={styles.proCardTitle}>{purchase.isPro ? t.proActive : t.unlockTitle}</Text><Text style={styles.proCardText}>{purchase.isPro ? t.proActiveText : t.unlockText}</Text>{!purchase.isPro && <><Text style={styles.price}>{price} <Text style={styles.once}>{t.once}</Text></Text><Pressable style={[styles.proButton, !purchase.connected && styles.disabledButton]} disabled={!purchase.connected} onPress={() => void purchase.buy()}><Text style={styles.proButtonText}>{purchase.connected ? t.unlock : t.storeConnecting}</Text></Pressable><Pressable onPress={() => void purchase.restore()}><Text style={styles.restore}>{t.restore}</Text></Pressable></>}{purchase.message && <Text style={styles.purchaseError}>{purchase.message === 'NO_PURCHASE_FOUND' ? t.noPurchaseFound : purchase.message}</Text>}</View><Text style={styles.version}>WärmeTakt 1.0.0 · Kamilunavo</Text></ScrollView>;
}

function Navigation({ screen, setScreen, t }: { screen: Screen; setScreen: (s: Screen) => void; t: any }) { const items: { key: Screen; icon: string; label: string }[] = [{ key: 'home', icon: '⌂', label: t.home }, { key: 'tests', icon: '↗', label: t.tests }, { key: 'entry', icon: '＋', label: t.entry }, { key: 'settings', icon: '⚙', label: t.settings }]; return <View style={styles.nav}>{items.map((item) => <Pressable key={item.key} style={styles.navItem} onPress={() => setScreen(item.key)}><Text style={[styles.navIcon, screen === item.key && styles.navActive]}>{item.icon}</Text><Text style={[styles.navLabel, screen === item.key && styles.navActive]}>{item.label}</Text></Pressable>)}</View>; }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.white }, app: { flex: 1, backgroundColor: colors.cream }, content: { flex: 1 },
  header: { height: 76, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.line },
  brand: { color: colors.ink, fontSize: 24, fontWeight: '800', letterSpacing: -0.8 }, brandLine: { color: colors.teal, fontSize: 9, fontWeight: '800', letterSpacing: 2.2, marginTop: 1 }, proPill: { backgroundColor: colors.mint, borderRadius: 20, paddingHorizontal: 13, paddingVertical: 8 }, proPillText: { color: colors.tealDark, fontWeight: '800', fontSize: 12 }, scroll: { padding: 22, paddingBottom: 36 },
  eyebrow: { color: colors.teal, fontWeight: '800', fontSize: 11, letterSpacing: 1.7, textTransform: 'uppercase', marginTop: 4 }, title: { color: colors.ink, fontSize: 31, lineHeight: 36, fontWeight: '800', letterSpacing: -1, marginTop: 7 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 20 },
  heroCard: { backgroundColor: colors.ink, borderRadius: 24, padding: 20 }, heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, heroLabel: { color: '#AFC1BF', fontSize: 12, fontWeight: '700' }, heroValue: { color: colors.lime, fontSize: 42, fontWeight: '800', letterSpacing: -1.5, marginTop: 2 }, scoreCircle: { width: 68, height: 68, borderRadius: 34, borderWidth: 5, borderColor: colors.teal, alignItems: 'center', justifyContent: 'center', flexDirection: 'row' }, score: { color: colors.white, fontWeight: '800', fontSize: 20 }, scoreOf: { color: '#9FB1AF', fontSize: 9, marginTop: 7 }, divider: { height: 1, backgroundColor: '#294344', marginVertical: 16 }, heroText: { color: colors.white, fontSize: 14, lineHeight: 20 }, miniRow: { flexDirection: 'row', marginTop: 18 }, metric: { flex: 1 }, metricValue: { color: colors.white, fontSize: 17, fontWeight: '800' }, metricLabel: { color: '#9FB1AF', fontSize: 10, lineHeight: 14, marginTop: 2 },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 25, marginBottom: 10 }, sectionTitle: { color: colors.ink, fontWeight: '800', fontSize: 17 }, link: { color: colors.teal, fontWeight: '700', fontSize: 12 }, testCard: { backgroundColor: colors.white, borderRadius: 18, padding: 16, flexDirection: 'row', borderWidth: 1, borderColor: colors.line }, testIcon: { width: 43, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.mint }, testIconText: { color: colors.teal, fontSize: 23, fontWeight: '800' }, testContent: { flex: 1, marginLeft: 13 }, testTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' }, testMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, progressTrack: { height: 6, borderRadius: 4, backgroundColor: '#E8EEEB', marginTop: 12 }, progressFill: { height: 6, borderRadius: 4, backgroundColor: colors.teal }, testHint: { color: colors.muted, fontSize: 10, marginTop: 7 },
  emptyCard: { backgroundColor: colors.white, borderRadius: 18, padding: 20, borderWidth: 1, borderStyle: 'dashed', borderColor: '#B9CAC5', marginBottom: 10 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: '800' }, emptyText: { color: colors.muted, fontSize: 13, lineHeight: 19, marginVertical: 8 },
  primaryButton: { backgroundColor: colors.teal, minHeight: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 18, paddingHorizontal: 16 }, primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: '800' }, disclaimer: { color: colors.muted, fontSize: 10, lineHeight: 15, textAlign: 'center', marginTop: 14, paddingHorizontal: 10 },
  resultCard: { backgroundColor: colors.white, borderRadius: 22, padding: 20, borderWidth: 1, borderColor: colors.line, marginBottom: 12 }, badge: { color: colors.amber, backgroundColor: '#FFF4DF', fontSize: 10, fontWeight: '800', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 10, alignSelf: 'flex-start', overflow: 'hidden' }, resultTitle: { color: colors.ink, fontSize: 21, fontWeight: '800', marginTop: 13 }, settingChange: { color: colors.teal, fontSize: 26, fontWeight: '800', marginTop: 5 }, compareRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.line }, compareLabel: { color: colors.muted, fontSize: 10, textTransform: 'uppercase', fontWeight: '700' }, compareValue: { color: colors.ink, fontWeight: '800', fontSize: 16, marginTop: 4 }, resultNote: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 18 },
  wizardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }, stepLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' }, optionCard: { minHeight: 56, borderRadius: 15, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, optionActive: { borderColor: colors.teal, backgroundColor: colors.mint }, optionText: { color: colors.ink, fontSize: 14, fontWeight: '700', flex: 1 }, optionTextActive: { color: colors.tealDark }, radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: '#AAB9B6', marginRight: 12 }, radioActive: { borderWidth: 5, borderColor: colors.teal }, infoCard: { backgroundColor: '#EEF6F7', borderRadius: 15, padding: 15, marginTop: 13 }, infoTitle: { color: colors.tealDark, fontSize: 13, fontWeight: '800' }, infoText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, summaryCard: { backgroundColor: colors.white, borderRadius: 18, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 17 }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.line }, summaryLabel: { color: colors.muted, fontSize: 12 }, summaryValue: { color: colors.ink, fontSize: 13, fontWeight: '800', maxWidth: '62%', textAlign: 'right' }, confirmCard: { backgroundColor: colors.white, borderRadius: 17, borderWidth: 1, borderColor: colors.line, padding: 15, flexDirection: 'row', alignItems: 'flex-start', marginTop: 14 }, confirmActive: { borderColor: colors.teal, backgroundColor: colors.mint }, checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: '#AAB9B6', marginRight: 11, alignItems: 'center', justifyContent: 'center' }, checkboxActive: { backgroundColor: colors.teal, borderColor: colors.teal }, checkmark: { color: colors.white, fontWeight: '900' }, confirmText: { color: colors.ink, fontSize: 12, lineHeight: 18, flex: 1 }, wizardActions: { flexDirection: 'row', gap: 10, marginTop: 2 }, wizardPrimary: { flex: 1 }, secondaryButton: { flex: 0.65, minHeight: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white }, secondaryButtonText: { color: colors.ink, fontSize: 14, fontWeight: '800' }, disabledButton: { opacity: 0.5 },
  formCard: { backgroundColor: colors.white, borderRadius: 22, padding: 18, borderWidth: 1, borderColor: colors.line }, field: { marginBottom: 16 }, fieldLabel: { color: colors.ink, fontSize: 13, fontWeight: '700', marginBottom: 7 }, inputWrap: { height: 50, borderWidth: 1, borderColor: colors.line, borderRadius: 13, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAFBF9' }, input: { flex: 1, color: colors.ink, fontSize: 17, fontWeight: '700', paddingHorizontal: 14, height: '100%' }, unit: { color: colors.muted, fontSize: 13, fontWeight: '700', paddingRight: 14 }, formHint: { color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 12 },
  settingsCard: { backgroundColor: colors.white, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: colors.line, marginTop: 20 }, segment: { flexDirection: 'row', backgroundColor: colors.cream, padding: 4, borderRadius: 13 }, segmentItem: { flex: 1, paddingVertical: 11, alignItems: 'center', borderRadius: 10 }, segmentActive: { backgroundColor: colors.white }, segmentText: { color: colors.muted, fontWeight: '700' }, segmentTextActive: { color: colors.tealDark }, proCard: { backgroundColor: colors.ink, borderRadius: 24, padding: 22, marginTop: 18 }, proCardEyebrow: { color: colors.lime, fontSize: 10, fontWeight: '800', letterSpacing: 1.8 }, proCardTitle: { color: colors.white, fontSize: 24, fontWeight: '800', marginTop: 9 }, proCardText: { color: '#B7C6C4', fontSize: 13, lineHeight: 20, marginTop: 8 }, price: { color: colors.white, fontSize: 27, fontWeight: '800', marginTop: 18 }, once: { color: '#AFC1BF', fontSize: 12, fontWeight: '500' }, proButton: { backgroundColor: colors.lime, borderRadius: 14, padding: 15, alignItems: 'center', marginTop: 15 }, proButtonText: { color: colors.ink, fontWeight: '800' }, restore: { color: '#AFC1BF', textAlign: 'center', fontSize: 11, marginTop: 13 }, purchaseError: { color: '#FFB7A8', textAlign: 'center', fontSize: 11, lineHeight: 16, marginTop: 10 }, version: { color: colors.muted, textAlign: 'center', fontSize: 10, marginTop: 18 },
  nav: { height: 70, paddingBottom: 5, flexDirection: 'row', backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.line }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' }, navIcon: { color: '#7E8D8C', fontSize: 21, height: 26 }, navLabel: { color: '#7E8D8C', fontSize: 9, fontWeight: '700' }, navActive: { color: colors.teal },
});
