export type Language = 'de' | 'en';
export const unitStrings = {
  de: { unitSystem: 'Temperatureinheit', celsius: 'Celsius (°C)', fahrenheit: 'Fahrenheit (°F)' },
  en: { unitSystem: 'Temperature unit', celsius: 'Celsius (°C)', fahrenheit: 'Fahrenheit (°F)' },
} as const;
export const flowStrings = {
  de: {
    settingNames: { heatingCurve: 'Heizkurve', flowTemperature: 'Maximale Vorlauftemperatur', hotWater: 'Warmwasser-Solltemperatur', hysteresis: 'Hysterese', roomTarget: 'Raum-Solltemperatur', other: 'Andere Einstellung' } as Record<string, string>,
    noActiveTest: 'Noch kein Test aktiv', noActiveTestText: 'Starte deinen ersten Vergleich und erfahre, ob eine Änderung wirklich Energie spart.', startFirstTest: 'Ersten Test starten', noTests: 'Noch keine Tests', noTestsText: 'WärmeTakt führt dich in drei kurzen Schritten durch deinen ersten Optimierungstest.', completed: 'ABGESCHLOSSEN', duration: 'Dauer', days: 'Tage',
    cancel: 'Abbrechen', step: 'Schritt', newExperiment: 'Neuer Test', chooseSetting: 'Was änderst du?', chooseSettingText: 'Wähle genau eine Einstellung aus, damit das Ergebnis aussagekräftig bleibt.', enterChange: 'Änderung festhalten.', enterChangeText: 'Trage den bisherigen und den neuen Wert direkt von deiner Wärmepumpe ein.', checkAndStart: 'Prüfen und starten.', checkText: 'Kontrolliere die Angaben. WärmeTakt beginnt danach mit dem Vergleich.', previousValue: 'Bisheriger Wert', newValue: 'Neuer Wert', testDuration: 'Messzeitraum', oneChangeOnly: 'Nur eine Einstellung verändern', oneChangeOnlyText: 'Weitere Änderungen während des Tests würden das Ergebnis verfälschen.', setting: 'Einstellung', change: 'Änderung', safetyConfirm: 'Ich habe die Herstellervorgaben geprüft und verändere keine sicherheitsrelevanten Grenzwerte.', back: 'Zurück', continue: 'Weiter', startTest: 'Test starten',
    proActive: 'Pro ist freigeschaltet.', proActiveText: 'Alle Tests und zukünftigen Pro-Funktionen stehen dauerhaft zur Verfügung.', storeConnecting: 'Store wird verbunden …', noPurchaseFound: 'Es wurde kein früherer Kauf gefunden.',
  },
  en: {
    settingNames: { heatingCurve: 'Heating curve', flowTemperature: 'Maximum flow temperature', hotWater: 'Hot water target', hysteresis: 'Hysteresis', roomTarget: 'Indoor temperature target', other: 'Other setting' } as Record<string, string>,
    noActiveTest: 'No active test yet', noActiveTestText: 'Start your first comparison and see whether a change actually saves energy.', startFirstTest: 'Start first test', noTests: 'No tests yet', noTestsText: 'WärmeTakt guides you through your first optimization test in three short steps.', completed: 'COMPLETED', duration: 'Duration', days: 'days',
    cancel: 'Cancel', step: 'Step', newExperiment: 'New test', chooseSetting: 'What are you changing?', chooseSettingText: 'Select exactly one setting so the result remains meaningful.', enterChange: 'Record the change.', enterChangeText: 'Enter the previous and new values shown by your heat pump.', checkAndStart: 'Review and start.', checkText: 'Check the details. WärmeTakt will then begin the comparison.', previousValue: 'Previous value', newValue: 'New value', testDuration: 'Measurement period', oneChangeOnly: 'Change one setting only', oneChangeOnlyText: 'Additional changes during the test would distort the result.', setting: 'Setting', change: 'Change', safetyConfirm: 'I have checked the manufacturer instructions and will not alter safety-related limits.', back: 'Back', continue: 'Continue', startTest: 'Start test',
    proActive: 'Pro is unlocked.', proActiveText: 'All tests and future Pro features are permanently available.', storeConnecting: 'Connecting to store…', noPurchaseFound: 'No previous purchase was found.',
  },
} as const;
export const strings = {
  de: { pro: 'PRO', overview: 'Deine Anlage', greeting: 'Guten Überblick.', intro: 'Erkenne, welche Einstellungen deine Wärmepumpe wirklich effizienter machen.', efficiencyChange: 'Wetterbereinigte Verbesserung', resultPositive: 'Deine letzte Änderung spart voraussichtlich Energie – ohne erkennbaren Komfortverlust.', resultWaiting: 'Für ein belastbares Ergebnis werden weitere vergleichbare Messungen benötigt.', cop: 'Ø COP', fewerStarts: 'weniger Starts', comfort: 'Raumkomfort', activeTest: 'Aktiver Test', details: 'Details', heatingCurve: 'Heizkurve absenken', dayOfTest: 'Tag 4 von 7 · 0,6 → 0,5', weatherAdjusted: 'Außentemperatur wird berücksichtigt', addMeasurement: 'Tageswerte erfassen', disclaimer: 'WärmeTakt gibt Optimierungshinweise und ersetzt keine sicherheitsrelevanten Herstellervorgaben oder Fachplanung.', experiments: 'Optimierung', testsTitle: 'Einstellung testen.', testsIntro: 'Ändere immer nur eine Einstellung. So lässt sich ihre Wirkung zuverlässig erkennen.', inProgress: 'LÄUFT', before: 'Vorher', after: 'Nachher', adjusted: 'Bereinigt', needMoreDays: 'Noch drei Messtage bis zur belastbaren Auswertung. Raumtemperatur und Wetter bleiben im Vergleich enthalten.', newTest: 'Neuen Test starten', dailyValues: 'Messung', entryTitle: 'Tageswerte erfassen.', entryIntro: 'Übernimm die Werte aus der Anzeige deiner Wärmepumpe oder von externen Zählern.', electricity: 'Stromverbrauch', generatedHeat: 'Erzeugte Wärmemenge', outsideTemp: 'Mittlere Außentemperatur', roomTemp: 'Mittlere Raumtemperatur', compressorStarts: 'Verdichterstarts', count: 'Anzahl', saveAndAnalyze: 'Speichern & auswerten', localStorage: 'Die Daten werden zunächst ausschließlich auf diesem Gerät gespeichert.', settings: 'Einstellungen', settingsTitle: 'Deine WärmeTakt-App.', language: 'Sprache', unlockTitle: 'Mehr aus deiner Anlage holen.', unlockText: 'Unbegrenzte Tests, Langzeitvergleich, CSV-Import, PDF-Berichte und zukünftige automatische Verbindungen.', once: 'einmalig', unlock: 'Pro dauerhaft freischalten', restore: 'Käufe wiederherstellen', home: 'Übersicht', tests: 'Tests', entry: 'Erfassen' },
  en: { pro: 'PRO', overview: 'Your system', greeting: 'Heat, made clear.', intro: 'See which settings actually make your heat pump more efficient.', efficiencyChange: 'Weather-adjusted improvement', resultPositive: 'Your latest change is likely saving energy – without a noticeable loss of comfort.', resultWaiting: 'More comparable readings are needed for a reliable result.', cop: 'Avg. COP', fewerStarts: 'fewer starts', comfort: 'Indoor comfort', activeTest: 'Active test', details: 'Details', heatingCurve: 'Lower heating curve', dayOfTest: 'Day 4 of 7 · 0.6 → 0.5', weatherAdjusted: 'Outdoor temperature is accounted for', addMeasurement: 'Add daily readings', disclaimer: 'WärmeTakt provides optimization guidance and does not replace safety-related manufacturer instructions or professional planning.', experiments: 'Optimization', testsTitle: 'Test a setting.', testsIntro: 'Change only one setting at a time. This makes its effect measurable.', inProgress: 'IN PROGRESS', before: 'Before', after: 'After', adjusted: 'Adjusted', needMoreDays: 'Three more measurement days are needed for a reliable result. Indoor temperature and weather remain part of the comparison.', newTest: 'Start a new test', dailyValues: 'Measurement', entryTitle: 'Add daily readings.', entryIntro: 'Enter the values shown by your heat pump or external meters.', electricity: 'Electricity use', generatedHeat: 'Heat generated', outsideTemp: 'Average outdoor temperature', roomTemp: 'Average indoor temperature', compressorStarts: 'Compressor starts', count: 'Count', saveAndAnalyze: 'Save & analyze', localStorage: 'For now, your data is stored exclusively on this device.', settings: 'Settings', settingsTitle: 'Your WärmeTakt app.', language: 'Language', unlockTitle: 'Get more from your system.', unlockText: 'Unlimited tests, long-term comparisons, CSV import, PDF reports, and future automated connections.', once: 'one-time', unlock: 'Unlock Pro permanently', restore: 'Restore purchases', home: 'Overview', tests: 'Tests', entry: 'Add' },
} as const;
